[package]
name = "logitech-led-sdk"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]
logitech-led-sdk-sys = { path = "logitech-led-sdk-sys" }

[dev-dependencies]
serial_test = "0.4.0"

[workspace]
members = [
	"logitech-led-sdk-sys"
]
